[package]
name = "neon-miniaudio"
version = "0.1.0"
authors = ["YXL <chenxin.lan.76@gmail.com>"]
license = "MIT"
build = "build.rs"
edition = "2018"
exclude = ["artifacts.json", "index.node"]

[lib]
name = "neon_miniaudio"
crate-type = ["cdylib"]

[build-dependencies]
neon-build = "0.4.0"

[dependencies]
neon = "0.4.0"
miniaudio = "0.10.0"

[profile.release]
lto = true
