name: Build

on:
  push:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: Test on ${{ matrix.os }}
    steps:
      - name: Install LLVM (Windows)
        if: matrix.os == 'windows-latest'
        run: choco install llvm

      - name: Installing needed Ubuntu dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev

      - name: Checkout
        uses: actions/checkout@v2

      - run: cargo build
